### ISSUE TITLE
AdguardHome can't be download

### ISSUE THREAD

**Issue by doumeki** [xiaoqingfengATGH/feeds-xiaoqingfeng#3]
AdguradHome又不能下载了

**Comment by xiaoqingfengATGH** [comment]
如果你是说在AdGuardHome的界面里，不能升级？

界面内容都是AdGuardHome提供的，确认网络没问题，基本都可以更新成功。

如果是说编译，已经确认可以下载到最新版本。

编译前，记得make dirclean
